flowchart LR

    subgraph staging
        staging_stg_airports["staging.stg_airports<br/>(table)"]
        staging_stg_crew_assignments["staging.stg_crew_assignments<br/>(table)"]
        staging_stg_employees["staging.stg_employees<br/>(table)"]
        staging_stg_flights["staging.stg_flights<br/>(table)"]
        staging_stg_routes["staging.stg_routes<br/>(table)"]
    end

    subgraph dds
        dds_dim_airports["dds.dim_airports<br/>(table)"]
        dds_dim_employees["dds.dim_employees<br/>(table)"]
        dds_dim_routes["dds.dim_routes<br/>(table)"]
        dds_fact_crew_assignments["dds.fact_crew_assignments<br/>(table)"]
        dds_fact_flights["dds.fact_flights<br/>(incremental)"]
    end

    subgraph mart
        mart_mart_airport_statistics["mart.mart_airport_statistics<br/>(view)"]
        mart_mart_crew_utilization["mart.mart_crew_utilization<br/>(view)"]
        mart_mart_flight_performance["mart.mart_flight_performance<br/>(view)"]
    end

    staging_stg_airports --> dds_dim_airports
    staging_stg_crew_assignments --> dds_fact_crew_assignments
    staging_stg_employees --> dds_dim_employees
    staging_stg_flights --> dds_fact_flights
    staging_stg_routes --> dds_dim_routes
    dds_dim_airports --> mart_mart_airport_statistics
    dds_dim_airports --> mart_mart_flight_performance
    dds_dim_employees --> dds_fact_crew_assignments
    dds_dim_employees --> mart_mart_airport_statistics
    dds_dim_employees --> mart_mart_crew_utilization
    dds_dim_routes --> dds_fact_crew_assignments
    dds_dim_routes --> dds_fact_flights
    dds_dim_routes --> mart_mart_airport_statistics
    dds_dim_routes --> mart_mart_crew_utilization
    dds_dim_routes --> mart_mart_flight_performance
    dds_fact_crew_assignments --> mart_mart_crew_utilization
    dds_fact_flights --> dds_fact_crew_assignments
    dds_fact_flights --> mart_mart_airport_statistics
    dds_fact_flights --> mart_mart_crew_utilization
    dds_fact_flights --> mart_mart_flight_performance
